CREATE TABLE dbo.CONTACT
(
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	EMAIL_ADDRESS VARCHAR(50)
)

SELECT * FROM dbo.CONTACT;

TRUNCATE TABLE dbo.CONTACT;

INSERT dbo.CONTACT
	(FIRST_NAME, LAST_NAME, EMAIL_ADDRESS)
VALUES
	('RAYMOND', 'BARLEY', 'RAYMONDBARLEY@GMAIL.COM')

INSERT dbo.CONTACT
	(FIRST_NAME, LAST_NAME, EMAIL_ADDRESS)
VALUES
	('KAREN', 'BARLEY', 'KARENBARLEY@GMAIL.COM')